version: "3.8"
services:
  sandbox:
    build: .
    ports:
      - "80:5000"
    expose:
      - 80
#    deploy:
#      restart_policy:
#        condition: any
#        delay: 5s
#        max_attempts: 5
#        window: 120s
