version: "3.7"
services:
  flask:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./RequestsTrainer:/opt/RequestsTrainer
    environment:
      - FLASK_APP=/opt/RequestsTrainer
      - FLASK_ENV=development
      
